"""Micropolis city-sim runner + serializer into the fbsim-core turn-major schema."""

import json
import os
import subprocess
from pathlib import Path
from typing import Literal

from dotenv import load_dotenv

PKG_DIR = Path(__file__).resolve().parent.parent  # forecastbench-sim/worlds/micropolis
FBS_DIR = PKG_DIR.parent.parent  # forecastbench-sim
DATA_DIR = FBS_DIR / "data" / "micropolis"

load_dotenv(PKG_DIR / ".env")
MICROPOLIS_APP_PATH = Path(os.environ["MICROPOLIS_CORE_PATH"]) / "apps" / "micropolis"

CITY_CHOICES = [
    "about",
    "badnews",
    "bluebird",
    "bruce",
    "deadwood",
    "finnigan",
    "freds",
    "haight",
    "happisle",
    "joffburg",
    "kamakura",
    "kobe",
    "kowloon",
    "kyoto",
    "linecity",
    "med_isle",
    "ndulls",
    "neatmap",
    "radial",
    "scenario_bern",
    "scenario_boston",
    "scenario_detroit",
    "scenario_dullsville",
    "scenario_hamburg",
    "scenario_rio_de_janeiro",
    "scenario_san_francisco",
    "scenario_tokyo",
    "senri",
    "southpac",
    "splats",
    "wetcity",
    "yokohama",
]


def _load_jsonl(file_path: Path) -> list[dict]:
    """Load a JSONL file and return a list of dicts."""
    with open(file_path, "r") as f:
        return [json.loads(line) for line in f if line.strip()]


class CitySimulation:
    """Class to run a Micropolis city simulation and collect metrics."""

    def __init__(self, city_name: str, seed: int, disasters: bool = False):
        self.city_name = city_name
        self.seed = seed
        self.disasters = disasters
        self.log_data: list[dict] | None = None
        self.events_data: list[dict] | None = None

    def run(self, nturns: int, quiet: bool = True) -> None:
        """Run the simulation for a given number of turns."""
        args = [
            "--city",
            self.city_name,
            "--seed",
            str(self.seed),
            "--turns",
            str(nturns),
            "--output-base-dir",
            DATA_DIR,
        ]
        if self.disasters:
            args.append("--disasters")
        else:
            args.append("--no-disasters")

        result = subprocess.run(
            ["pnpm", "run", "run-sim", *args],
            cwd=MICROPOLIS_APP_PATH,
            check=False,
            stdout=subprocess.DEVNULL if quiet else None,
            stderr=subprocess.DEVNULL if quiet else None,
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"micropolis run-sim failed with exit code {result.returncode}"
            )

    def _get_data_file_path(self, kind: Literal["log", "events"]) -> Path:
        """Get the path to the data file generated by the simulation."""
        disasters_str = "" if self.disasters else "-nodisasters"
        filename = f"{kind}-seed{self.seed}{disasters_str}.jsonl"
        return DATA_DIR / self.city_name / filename

    def load_from_disk(self) -> None:
        """Load the simulation data from disk and return it in the core schema."""
        log_path = self._get_data_file_path("log")
        events_path = self._get_data_file_path("events")

        if not log_path.exists():
            raise FileNotFoundError(f"Simulation log file not found: {log_path}")
        if not events_path.exists():
            raise FileNotFoundError(f"Simulation events file not found: {events_path}")

        self.log_data = _load_jsonl(log_path)
        self.events_data = _load_jsonl(events_path)


N_REGIONS_DEFAULT = 2
N_TURNS = 90
METRICS = ["population", "funds", "pollution"]


def run_region(
    growth_rate: float, policy_enabled: bool, seed: int, **policy_kwargs
) -> dict:
    """Run one city/region's simulation; return per-turn metric arrays.

    Args:
        growth_rate: TODO — placeholder scenario parameter analogous to pandemic's beta.
        policy_enabled: TODO — whether the intervention (e.g. zoning/tax policy) is active.
        seed: RNG seed for reproducibility.
        **policy_kwargs: TODO — intervention-specific parameters (e.g. policy_turn, magnitude).

    Returns:
        dict mapping metric name -> list of per-turn values, length N_TURNS.
    """
    raise NotImplementedError("TODO: implement Micropolis city simulation")


def to_world(region_series: dict[int, dict], names: dict[int, str]) -> dict:
    """Assemble game_data in the core TURN-MAJOR schema:
    time_series[metric][turn][region_id] = value.
    """
    ts = {m: {} for m in METRICS}
    for rid, series in region_series.items():
        for m in METRICS:
            for turn, val in enumerate(series[m]):
                ts[m].setdefault(str(turn), {})[str(rid)] = val
    return {
        "time_series": ts,
        "civilizations": {
            str(rid): {"name": names[rid], "nation_id": str(rid)}
            for rid in region_series
        },
    }
